<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <RootNamespace>EveConv.Memory.Tests</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Moq" />
    <PackageReference Include="dotenv.net" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Memory\EveConv.Memory\EveConv.Memory.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".env" Condition="Exists('.env')">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
