<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Packages.props', '$(MSBuildThisFileDirectory)../'))"
          Condition="$([MSBuild]::GetPathOfFileAbove('Directory.Packages.props', '$(MSBuildThisFileDirectory)../')) != ''" />

  <ItemGroup>
    <PackageVersion Include="Microsoft.ML.OnnxRuntime" Version="$(HFTKVersion)" />
  </ItemGroup>
</Project>
