<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Packages.props', '$(MSBuildThisFileDirectory)../'))"
          Condition="$([MSBuild]::GetPathOfFileAbove('Directory.Packages.props', '$(MSBuildThisFileDirectory)../')) != ''" />
  <ItemGroup>
    <PackageVersion Include="Qdrant.Client" Version="1.15.1" />
  </ItemGroup>
</Project>
