<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <!-- Custom Properties -->
    <MSEXVersion>10.0.1</MSEXVersion>
    <ASPNETVersion>10.0.1</ASPNETVersion>
  </PropertyGroup>
  <ItemGroup>
    <!-- Dependency Injection -->
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="$(MSEXVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="$(MSEXVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="$(MSEXVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="$(MSEXVersion)" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="$(MSEXVersion)" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="$(MSEXVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="$(MSEXVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="$(MSEXVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="$(MSEXVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="$(MSEXVersion)" />
    <!-- Web -->
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="$(ASPNETVersion)" />
    <PackageVersion Include="Swashbuckle.AspNetCore.SwaggerUI" Version="$(ASPNETVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="$(MSEXVersion)" />
    <!-- AI -->
    <PackageVersion Include="Microsoft.Extensions.AI.Abstractions" Version="$(MSEXVersion)" />
    <PackageVersion Include="Microsoft.Extensions.AI" Version="$(MSEXVersion)" />
    <PackageVersion Include="Microsoft.Extensions.AI.OpenAI" Version="10.3.0" />
    <PackageVersion Include="Microsoft.Extensions.VectorData.Abstractions" Version="9.7.0" />
    <!-- Utils -->
    <PackageVersion Include="dotenv.net" Version="4.0.0" />
    <PackageVersion Include="MessagePack" Version="3.1.4" />
    <PackageVersion Include="SqlSugarCore" Version="5.1.4.214" />
    <PackageVersion Include="Scriban" Version="7.2.4" />
  </ItemGroup>
</Project>
