<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Packages.props', '$(MSBuildThisFileDirectory)../'))" Condition="$([MSBuild]::GetPathOfFileAbove('Directory.Packages.props', '$(MSBuildThisFileDirectory)../')) != ''" />
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Caching.Memory" Version="$(MSEXVersion)" />
    <PackageVersion Include="AWSSDK.S3" Version="4.0.13.1" />
  </ItemGroup>
</Project>
