<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
		<Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Connectors\EveConv.Connectors.Onnx\EveConv.Connectors.Onnx.csproj" />
    <ProjectReference Include="..\..\Embedder\EveConv.Embedder\EveConv.Embedder.csproj" />
    <ProjectReference Include="..\..\Reference\EveConv.MimeType\EveConv.MimeType.csproj" />
    <ProjectReference Include="..\..\Tokenizer\EveConv.HuggingFaceFastTokenizer\EveConv.HuggingFaceFastTokenizer.csproj" />
    <ProjectReference Include="..\EveConv.Plugins.Api\EveConv.Plugins.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="plugin.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
