<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Reference\Channel\EveConv.Channel.Client\EveConv.Channel.Client.csproj" />
    <ProjectReference Include="..\..\Reference\Channel\EveConv.Channel.Server\EveConv.Channel.Server.csproj" />
  </ItemGroup>

</Project>
