<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Packages.props', '$(MSBuildThisFileDirectory)../'))"
          Condition="$([MSBuild]::GetPathOfFileAbove('Directory.Packages.props', '$(MSBuildThisFileDirectory)../')) != ''" />
  <ItemGroup>
    <PackageVersion Include="NetMQ" Version="4.0.2.2" />
  </ItemGroup>
</Project>
