// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace EveConv.HuggingFaceFastTokenizer.Raw
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "hf_tokenizers_c";





        [DllImport(__DllName, EntryPoint = "tokenizers_new_from_str", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern TokenizerWrapper* tokenizers_new_from_str(byte* input_cstr, nuint len);

        [DllImport(__DllName, EntryPoint = "tokenizers_new_from_file", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern TokenizerWrapper* tokenizers_new_from_file(byte* filepath_cstr, nuint len);

        [DllImport(__DllName, EntryPoint = "tokenizers_new_from_bytes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern TokenizerWrapper* tokenizers_new_from_bytes(byte* byte_array, nuint len);

        [DllImport(__DllName, EntryPoint = "byte_level_bpe_tokenizers_new_from_str", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern TokenizerWrapper* byte_level_bpe_tokenizers_new_from_str(byte* input_vocab_str, nuint len_vocab, byte* input_merges_str, nuint len_merges, byte* input_added_tokens_str, nuint len_added_tokens);

        [DllImport(__DllName, EntryPoint = "tokenizers_encode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int tokenizers_encode(TokenizerWrapper* handle, byte* input_cstr, nuint len, int add_special_tokens, TokenizerEncodeResult* out_result);

        [DllImport(__DllName, EntryPoint = "tokenizers_encode_batch", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int tokenizers_encode_batch(TokenizerWrapper* handle, byte** input_cstr, nuint* input_len, nuint num_seqs, int add_special_tokens, TokenizerEncodeResult* out_result);

        [DllImport(__DllName, EntryPoint = "tokenizers_free_encode_results", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void tokenizers_free_encode_results(TokenizerEncodeResult* results, nuint num_seqs);

        [DllImport(__DllName, EntryPoint = "tokenizers_decode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int tokenizers_decode(TokenizerWrapper* handle, uint* input_ids, nuint len, int skip_special_tokens, TokenizerDecodeResult* out_result);

        [DllImport(__DllName, EntryPoint = "tokenizers_decode_batch", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int tokenizers_decode_batch(TokenizerWrapper* handle, uint** input_sentences, nuint* input_lens, nuint num_seqs, int skip_special_tokens, TokenizerDecodeResult* out_result);

        [DllImport(__DllName, EntryPoint = "tokenizers_free_decode_results", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void tokenizers_free_decode_results(TokenizerDecodeResult* sentences, nuint num_seqs);

        [DllImport(__DllName, EntryPoint = "tokenizers_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void tokenizers_free(TokenizerWrapper* wrapper);

        [DllImport(__DllName, EntryPoint = "tokenizers_get_vocab_size", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void tokenizers_get_vocab_size(TokenizerWrapper* handle, nuint* size);

        [DllImport(__DllName, EntryPoint = "tokenizers_id_to_token", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int tokenizers_id_to_token(TokenizerWrapper* handle, uint id, TokenizerDecodeResult* out_result);

        [DllImport(__DllName, EntryPoint = "tokenizers_token_to_id", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int tokenizers_token_to_id(TokenizerWrapper* handle, byte* token, nuint len, uint* out_id);

        [DllImport(__DllName, EntryPoint = "tokenizers_get_last_error", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void tokenizers_get_last_error(byte** out_cstr, nuint* out_len);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct TokenizerWrapper
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct TokenizerEncodeResult
    {
        public uint* token_ids;
        public nuint len;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct TokenizerDecodeResult
    {
        public byte* chars;
        public nuint len;
    }



}
